---
title: "Mitox data review"
author: "Anna Petouhoff"
date: "2025-03-11"
output: html_document
---

```{r}
library(ggplot2)
library(ggrepel)
library(tidyverse)
library(ggfortify)
library(vegan)
library(grid)
```

# load data 
```{r}
load("../data/Cohort_2/ra-long.rds")
load("../data/Cohort_2/clinical.rds")
load("../data/Cohort_2/mitox_microbiome_metadata.rds")
load("../data/Cohort_2/counts-wide.rds")
load("../data/Cohort_2/phylum-labels.rds")
load("../data/Cohort_2/taxonomy-key.rds")
load("../data/Cohort_2/ANCOM-BC2_response_baseline.RData")
```


# Figure Feature
```{r}
colors <- c("#6699CC", "#999933", "#CC6677","#44AA99","#DDCC77","#882255")
colors <- c("cyan4", "darkgoldenrod2", "darkgreen", "salmon2", "cornflowerblue", "deeppink4") 

# Response ID's
resp.id <- mic.meta %>%
  left_join(demographics) %>%
  select(sample, Days, PPI, Response) %>%
  mutate(PPI = if_else(is.na(PPI), 'No', as.character(PPI)))

# baseline samples 
base.samps <- mic.meta %>% 
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10)
```

# Stacked Bar
```{r}
phyl.ra <- ra.l %>%
  filter(grepl("p__", microbe))

top.phyl <- phyl.ra %>%
  group_by(microbe) %>%
  summarise(med.abun = median(RelAbun)) %>%
  arrange(desc(med.abun)) %>%
  filter(med.abun > 0)

phyl.ra <- phyl.ra %>%
  mutate(Phylum = ifelse(microbe %in% top.phyl$microbe, gsub("p__", "", microbe), 
                         "Other")) %>%
  left_join(resp.id)

# reorder samples by the total relative abundance of Firmicutes
phyl.ra <- phyl.ra %>%
  group_by(sample) %>%
  mutate(Firmicutes_Abundance = sum(RelAbun[Phylum == "Firmicutes"], na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(sample = fct_reorder(sample, Firmicutes_Abundance))

# order of microbes with 'other' last
phyl.ra <- phyl.ra %>%
  mutate(Phylum = factor(Phylum, levels = c(
    "Firmicutes", 
    setdiff(unique(Phylum), c("Firmicutes", "Other")), 
    "Other")))

phyl.ra %>%
  filter(sample %in% base.samps$sample) %>%
  ggplot(aes(x = sample, y = RelAbun, fill = Phylum)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_fill_manual(values = colors) + 
  labs(x = "", y = "") +
  theme_minimal(base_size = 9) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.major = element_blank(),
    legend.position = "top",
    legend.box = "horizontal",
    legend.title = element_blank(),
    strip.placement = "outside", # Moves facet labels outside
    strip.background = element_blank(), # Optional: Removes the background of facet labels
    strip.text.x = element_text(size = 9) # Adjusts facet label text size
  ) +
  facet_grid(~PPI, scales = "free_x", space = "free", switch = "x") +
  guides(fill = guide_legend(ncol = 6, nrow = 1, byrow = TRUE))

p_bar <- phyl.ra %>%
  filter(sample %in% base.samps$sample) %>%
  ggplot(aes(x = sample, y = RelAbun, fill = Phylum)) +
  geom_bar(position = "fill", stat = "identity", color = "white", linewidth = 0.1) +
  scale_fill_manual(values = colors) + 
  labs(x = "PPI Use", y = "") + 
  theme_minimal(base_size = 9) +
  theme(
    # Clean up axes
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    panel.grid = element_blank(),
    
    # PPI Use Title - added back and positioned
    axis.title.x = element_text(size = 7, face = "bold", margin = margin(t = 2)),
    
    # Legend settings - split into 2 rows and shrunk
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size = 6.8),
    legend.key.size = unit(0.2, "cm"),
    legend.spacing.y = unit(0.01, "cm"),
    legend.margin = margin(b = -5),
    
    # Combined strip.text.x to avoid the error
    # margin(t = 2) moves Yes/No closer to the plot
    strip.placement = "outside",
    strip.text.x = element_text(size = 7, face = "bold", margin = margin(t = -1, b = 0))
  ) +
  facet_grid(~PPI, scales = "free_x", space = "free", switch = "x") +
  guides(fill = guide_legend(
    nrow = 1,
    byrow = TRUE,
    override.aes = list(linewidth = 0)
  ))

ggsave("../figures/Figure3B.svg", device= "svg", height = 1.9, width = 4.5)
```


#Volcano Plot
```{r}
phyl_labels <- phyl_labels %>%
  mutate(taxon = substr(microbe, 4, nchar(microbe)))

res.recist <- res.recist %>%
  left_join(phyl_labels) %>%
  mutate(Phylum = ifelse(q_PPIYes < 0.05 & abs(lfc_PPIYes) > 1, 
                         ifelse(Phylum %in% phyl.ra$Phylum, Phylum, "Other"), NA),
         taxon = gsub("_", " ", taxon),
        Phylum = factor(Phylum, levels = c(
    "Firmicutes", "Bacteroidota", "Actinobacteria", "Proteobacteria", "Other")),
    label = taxon )

colors <- c("#6699CC", "#999933", "#CC6677","#44AA99","#882255")
colors <- c("cyan4", "darkgoldenrod2", "darkgreen", "salmon2", "deeppink4") 
```


```{r}

res_to_plot <- res.recist %>%
  filter(q_PPIYes < 1) %>%
  arrange(q_PPIYes) %>%
  mutate(display_label = case_when( row_number() <= 21    ~ as.character(label),       
                                    TRUE                  ~ ""))
y_max_val <- max(-log10(res_to_plot$q_PPIYes), na.rm = TRUE)
y_limit_plot <- y_max_val + 1.5 

g <- ggplot(res_to_plot, aes(x = lfc_PPIYes, y = -log10(q_PPIYes), label = display_label)) + 
  geom_point(aes(color = Phylum), alpha = 0.7, size = 1.2) + 
  geom_text_repel(
    size = 2.2,                
    max.overlaps = Inf,
    force = 4,                 
    box.padding = 0.3,         
    point.padding = 0.2,
    segment.size = 0.2,
    direction = "both"
  ) +
  scale_color_manual(values = colors, na.value = "honeydew3") +
  coord_cartesian(ylim = c(0, y_limit_plot), clip = "off") + 
  theme_bw(base_size = 9) +
  labs(x = "log2foldchange", y = "-log10(adj. p)") +
  theme(
    legend.position = "none", 
    panel.grid.minor = element_blank(),
    plot.margin = margin(t = 5, r = 10, b = 35, l = 10) 
  ) +
  annotate("segment", x = 1.5, xend = 4.5, y = -1.2, yend = -1.2,
           arrow = arrow(length = unit(0.1, "cm")), color = "black") +
  annotate("text", x = 3, y = -1.8, 
           label = "PPI Use", size = 3, fontface = "bold") +
  annotate("segment", x = -1.7, xend = -5.5, y = -1.2, yend = -1.2,
           arrow = arrow(length = unit(0.1, "cm")), color = "black") +
  annotate("text", x = -3.5, y = -1.8, 
           label = "No PPI Use", size = 3, fontface = "bold")


ggsave("../figures/Figure3E.svg", g, device = "svg", height = 2.5, width = 6)
```

# structural zero box blot 
```{r}
counts <- counts.w %>%
  pivot_longer(!microbe, names_to = "sample", values_to = "est.reads") %>%
  filter(grepl("s__", microbe)) %>%
  mutate(microbe = str_remove(microbe, "^[a-z]__"))

r <- counts %>%
  right_join(base.samps) %>%
  left_join(demographics) %>%

  filter(PPI == "YES",
         microbe %in% (struct0.recist %>% filter(`structural_zero (PPI = Yes)` &
                                                 !`structural_zero (PPI = No)`))$taxon) %>%
  select(sample, microbe, est.reads)

r.top <- r %>%
  group_by(microbe) %>%
  summarize(total.nonzero = sum(est.reads > 0),
            percent.nonzero = total.nonzero/n_distinct(sample),
            mean.counts = mean(est.reads)) %>%
  ungroup() 

nr <- counts %>%
  right_join(base.samps) %>%
  left_join(demographics) %>%
  filter(PPI == "No",
         microbe %in% (struct0.recist %>% filter(`structural_zero (PPI = Yes)` &
                                                 !`structural_zero (PPI = No)`))$taxon) %>%
  select(sample, microbe, est.reads) 

nr.top <- nr %>%
  group_by(microbe) %>%
    summarize(total.nonzero = sum(est.reads > 0),
            percent.nonzero = total.nonzero/n_distinct(sample),
            mean.counts = mean(est.reads)) %>%
  ungroup()

```

```{r}
top10 <- rbind(r.top, nr.top) %>%
  filter(percent.nonzero > 0.15) %>%
  arrange(desc(mean.counts)) %>%
  slice_head(n=10)

box.in <- rbind(r, nr) %>%
  filter(microbe %in% top10$microbe) %>%
  left_join(mic.meta) %>%
  left_join(demographics) %>%
  dplyr::rename(taxon = microbe) %>%
  left_join(phyl_labels) %>%
  mutate(Phylum = ifelse(Phylum %in% phyl.ra$Phylum, Phylum, "Other"),
         taxon = gsub("_", " ", taxon))


colors <- c("#999933","#6699CC","#44AA99")
colors <- c("darkgoldenrod2", "cyan4", "salmon2")
```


```{r}
box.in %>%
  ggplot(aes(x = taxon, y = log(est.reads), fill = Phylum)) +
  geom_boxplot(width = 0.5, outlier.shape = NA, alpha = 0.7) +
  geom_jitter(size = 0.5, alpha = 0.4, width = 0.2) + 
  scale_fill_manual(values = colors) +
  facet_grid(PPI ~ ., scales = "free_y", space = "free_y") +
  coord_flip() +
  theme_bw(base_size = 10) +
  theme(
    panel.spacing = unit(0.5, "lines"), 
    axis.text.y = element_text(face = "italic"), 
    strip.text = element_text(size = 10),
    legend.position = "none",
    plot.margin = margin(t = 5, r = 10, b = 5, l = 5),
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(
    title = "Taxa Found Only in the `No PPI Use` Group",
    x = "",
    y = "log(est. reads)"
  )

ggsave("../figures/Figure3F.svg", device = "svg", height = 2, width = 6.5)
```










