---
title: "Mitox Alpha Beta Diversity"
author: "Anna Petouhoff"
date: "2025-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(ROCR)
library(gdata)
library(vegan)
library(ggpubr)
library(ggforce)
```

```{r}
load("../data/Cohort_2/ra-long.rds")
load("../data/Cohort_2/ra-wide.rds")
load("../data/Cohort_2/clinical.rds")
load("../data/Cohort_2/mitox_microbiome_metadata.rds")
load("../data/Cohort_2/counts-long.rds")
```

```{r}
# Prepare clinical data
# baseline samples 
base.samps <- mic.meta %>% 
  group_by(`Patient Id`) %>%
  arrange(Days) %>%
  slice_head(n = 1) %>%
  ungroup() %>%
  filter(abs(Days) <= 10)

# Response ID's
resp.id <- mic.meta %>%
  left_join(demographics) %>%
  select(sample, PPI) %>%
  filter(sample %in% base.samps$sample) %>%
  mutate(PPI = if_else(is.na(PPI), 'No', as.character(PPI)))

```

# calculate alpha diversity with RA  
# shannon
```{r}
ra.in <- ra.l %>%
  filter(grepl("s__", microbe),
         sample %in% resp.id$sample)

ra.wide <- ra.in %>%
  pivot_wider(names_from = microbe, values_from = RelAbun, values_fill = 0)


shannon.index <- ra.wide %>%
  column_to_rownames("sample") %>%         
  diversity(index = "shannon") %>%
 tibble::enframe(name = "sample", value = "Shannon")


div.ra.resp <- shannon.index %>%
  left_join(resp.id) %>%
  select(-sample) %>% 
  pivot_longer(!PPI,
    names_to = "Signature",
               values_to = "Score") %>%
  mutate(data.type = "RA")

max_y <- max(div.ra.resp$Score, na.rm = TRUE)

alpha_diversity <- div.ra.resp %>%
 ggplot(aes(x = PPI, y = Score)) +
  geom_boxplot(aes(fill = PPI), width = 0.6, outlier.size = 0.5) + 
  scale_fill_manual(values = c("cornflowerblue", "lightsalmon2")) +
  labs(x = "PPI Use", y = "Shannon Index", title = "Alpha Diversity Comparison") +
  stat_compare_means(method = "t.test", size = 3, label.y = max_y * 0.99) + 
  theme_bw(base_size = 8) + 
  theme(
    legend.position = "none",
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.title = element_text(size = 8),
    axis.text = element_text(size = 8),
    strip.text = element_text(size = 8)
  ) +
  coord_cartesian(ylim = c(NA, max_y *1.15))


ggsave("../figures/Figure3C.svg", device = "svg", plot= alpha_diversity, height = 1.75, width = 3)
```


#calculate beta diversity
```{r}
wide_data<- ra.in %>%
  pivot_wider(names_from = microbe,
              values_from = RelAbun,
              values_fill = list(Relabun = 0))

bc_dist <- vegdist(wide_data[,-1], method = "bray")
```

```{r}
pca_result <- prcomp(bc_dist, scale. = FALSE)
scores <- data.frame(pca_result$x)
scores$sample <- rownames(scores)

scores <- pca_result$x %>%
  as.data.frame() %>%
  rownames_to_column(var = "Sample")
scores$PPI <- resp.id$PPI

ppi_colors <- c("Yes" = "lightsalmon2", "No" = "cornflowerblue")

group_means <- scores %>%
  group_by(PPI) %>%
  dplyr::summarize(PC1_mean = mean(PC1), PC2_mean = mean(PC2))
radius <- 1

beta_diversity <- ggplot(scores, aes(x = PC1, y = PC2, color = PPI)) +
  geom_point(size = 1) +
  scale_color_manual(values = ppi_colors) + 
  theme_minimal() +
  labs(x = "PC1", y = "PC2", title = "Beta Diveristy Comparison") +
  theme_minimal(base_size = 8) +
  geom_circle(data = group_means, aes(x0= PC1_mean, y0=PC2_mean, r=radius), inherit.aes=FALSE, color = "black", size =0.5) +
  theme(
    plot.title = element_text(size = 8, face = "bold"),
    legend.title = element_text("PPI Use"),           
    legend.text = element_text(size = 7),      
    legend.key.size = unit(0.3, "cm"),         
    legend.spacing.x = unit(0.1, "cm"),        
    legend.margin = margin(0, 0, 0, 0),        
    legend.box.margin = margin(-5, -5, -5, -5), 
    legend.position = "right" 
  )

  
beta_diversity

ggsave("../figures/Figure3D.svg", device = "svg", plot= beta_diversity, height = 1.5, width = 3)
```

# Running Statistics 
```{r}
wide_data$PPI <- resp.id$PPI
abundance <- ra.wide[,-1]

set.seed(9)
adonis2(bc_dist ~ PPI, data = wide_data, method = "bray")

adonis2(abundance ~ PPI, data = wide_data, method = "bray")
```

