---
title: "Heatmap"
author: "Anna Petouhoff"
date: "2025-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survival)
library(survminer)
library(glue)
library(RColorBrewer)
library(forcats)
library(UpSetR)
```

read in data
```{r}
db <- read.csv("T:/Labs/Spakowicz/ppiio/data/derived/2025-02-17/CoRR_formatted.csv")%>%
  select(vitalstatus, ppi, statin, immunotherapy, iostart, ppi_start, h2b_iostart, steroid_iostart, 
         abx_iostart, nsaid_iostart, cancer.name, PPI.days.to.iostart, H2B.days.to.iostart, days, ABX.days.to.iostart) %>%
   mutate(cancer.aggregated = ifelse(cancer.name %in% c("non-small cell lung cancer",
                                                         "melanoma",
                                                         "renal cell carcinoma",
                                                         "head and neck carcinoma"), 
                                      cancer.name,
                                      "Other"))
```


```{r}
check.window <- function(vect, per){
  wind <- per[1]:per[2]
  wind <- glue_collapse(as.character(wind), sep = ",|,")
  wind <- paste(",", wind, ",", sep = "")
  ifelse(grepl(pattern = wind, x = vect), 1, 0)
}

 db <- db %>%
   mutate(PPI.to.iostart = paste(",", PPI.days.to.iostart, ",", sep = ""),
          ppi_start = check.window(PPI.days.to.iostart, c(-28,28)))
 
db <- db %>% 
   mutate(H2B.to.iostart = paste(",", H2B.days.to.iostart, ",", sep = ""),
          h2b_start = check.window(H2B.days.to.iostart, c(-28,28)))

db <- db %>% 
  mutate(ABX.to.iostart = paste(",", ABX.days.to.iostart, ",", sep = ""),
         abx_start = check.window(ABX.days.to.iostart, c(-28,28)))
```

```{r define interesting columns}
meds_iostart <- c("h2b_iostart", "nsaid_iostart", "ppi", "statin", "steroid_iostart", "abx_start")

allcancers <- c('Other', 'melanoma', 'non-small cell lung cancer', 'renal cell carcinoma',"head and neck carcinoma")
```


# A+B) Survival curves of each medication at iostart
```{r create survival plots}
forms <- list()
for(var in meds_iostart){
  forms[[var]] <- as.formula(paste("Surv(days, vitalstatus) ~ ", var, sep = ""))
}
sfits <- surv_fit(formula = forms, data = db)
names(sfits) <- meds_iostart

almeds.plots <- ggsurvplot(sfits,
                           data = db,
                           pval = TRUE, 
                           conf.int = FALSE, 
                           risk.table = TRUE,
                           title = "Association of PPI with OS in all cancers", 
                           legend.title = "", 
                           legend.labs = list(c("Not prescribed", "Prescribed PPI's")),
                           xscale = "d_m",
                           break.time.by=365.25*2,
                           ylab = "Survival probability", 
                           xlab = "Months", 
                           palette = c("slateblue2", "lightsalmon2"), 
                           fontsize = 6, 
                           font.legend = list(size = 12))

```


```{r 6}
almeds.plots <- ggsurvplot(sfits,
                           data = db,
                           pval = TRUE, 
                           conf.int = FALSE, 
                           risk.table = TRUE,
                           title = "Association of H2B with OS in all cancers", 
                           legend.title = "", 
                           legend.labs = list(c("Not prescribed", "Prescribed H2B's")),
                           xscale = "d_m",
                           break.time.by=365.25*2,
                           ylab = "Survival probability", 
                           xlab = "Months", 
                           palette = c("slateblue2", "lightsalmon2"), 
                           fontsize = 6, 
                           font.legend = list(size = 12))
```





Heat map
```{r retain full cohort info for heatmap}
almeds.pval <- lapply(sfits, function (x) surv_pvalue(x)[1,2])
names(almeds.pval) <- names(sfits)
almeds.hr <- lapply(forms, function(x)  coefficients(summary(coxph(formula = x, data = db)))[,2])
almeds.pval <- bind_rows(almeds.pval)
almeds.hr <- bind_rows(almeds.hr)
almeds.dat <- as.data.frame(bind_rows(almeds.pval, almeds.hr))
rownames(almeds.dat) <- c("p.value", "hazrat")
almeds.dat <- almeds.dat %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "meds") %>%
  mutate(labcol = ifelse(hazrat < 1, "red", "black"),
         cancer = "All",) %>%
  select(cancer, meds, p.value, labcol)
  
```

```{r, message=FALSE, warning=FALSE, error=FALSE}
curvesbycancer <- list()
sfits <- list()
pvalbycancer <- list()
pvals <- list()
hrbycanc <- list()
hazrat <- list()
labcol <- list()
labs <- list()
canccox <- list()
coxmods <- list()
for(c in allcancers){
  
  tmp <- subset(db, db$cancer.aggregate == c)
  
  for(s in meds_iostart){
    
    f <- as.formula(paste("Surv(days, vitalstatus) ~ ", s, sep = ""))
    
    try ({
      sfits[[s]] <- surv_fit(formula = f, data = tmp)
      pvals[[s]] <- surv_pvalue(sfits[[s]])[1,2]
      
      x <- coefficients(summary(coxph(formula = f, data = tmp)))[,2]
      labs[[s]] <- ifelse(x < 1, "red", "black")
      
    })
  }
  
  curvesbycancer[[c]] <- sfits
  pvalbycancer[[c]] <- pvals
  labcol[[c]] <- labs
  canccox[[c]] <- bind_rows(coxmods)
  
  sfits <- list()
  pvals <- list()
  labs <- list()
  coxmods <- list()
}
allcancpvals <- bind_rows(pvalbycancer)
rownames(allcancpvals) <- names(pvalbycancer)
labcol <- bind_rows(labcol) 
rownames(labcol) <- names(pvalbycancer)
```

```{r}
labcol <- labcol %>%
  rownames_to_column(var = "cancer") %>%
  gather(key = "meds", value = "labcol", -cancer) %>%
  mutate(labcol = ifelse(is.na(labcol), "black", labcol))
heat.data <- allcancpvals  %>%
  rownames_to_column(var = "cancer") %>%
  gather(key = "meds", value = "p.value", -cancer) %>%
  full_join(labcol) %>%
  full_join(almeds.dat)
```

```{r}
heat.data <- bind_rows(almeds.dat, heat.data)
```

```{r fig.height=7, fig.width=6}
heat.plot <- heat.data %>%
  ggplot(aes(meds, fct_relevel(cancer, 'Other', 'melanoma', 'non-small cell lung cancer', 'renal cell carcinoma', "head and neck carcinoma", "All"))) +
  geom_tile(aes(fill = p.value)) +
  labs(x = "", y = "") +
  geom_point(aes(shape = labcol), size = 3) +
  scale_fill_distiller(guide = "legend", breaks = c(0.000000000001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.5, 1), 
                       limits = c(0, 1), values = c(0.000000000001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.5, 1),
                       type = "div", palette = "RdBu", direction = 1, 
                       labels = c("<0.01", "0.01", "0.02","0.03", "0.04","0.05","0.1", "0.2", "0.5", "1")) +
  scale_shape_manual(breaks = c("black", "red"), values = c("-", "+"), 
                     labels = c("HR>1", "HR<1"), name = "Direction") +
  theme_classic(base_size = 9) +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
    axis.title = element_blank(),
    legend.key.size = unit(0.3, "cm"),      # Shrinks the actual color boxes/shapes
    legend.text = element_text(size = 7),    # Shrinks the label text
    legend.title = element_text(size = 8),   # Shrinks the "p.value" and "Direction" titles
    legend.margin = margin(0, 0, 0, 0),      # Removes extra space around legends
    legend.spacing.y = unit(0.1, "cm")       # Tightens space between the two legends
  ) +
  scale_x_discrete(breaks = meds_iostart, 
                   labels = c("H2B", "NSAIDs", "PPI", "Statins", "CS", "ABx")) +
scale_y_discrete(
  breaks = c('Other', 'melanoma', 'non-small cell lung cancer',
             'renal cell carcinoma', 'head and neck carcinoma', 'All'),
  labels = c(
    'Other',
    'Melanoma',
    'Non-small cell\nlung cancer',
    'Renal cell\ncarcinoma',
    'Head and\nneck \ncarcinoma',
    'All'
  )
)
heat.plot

ggsave("../figures/Figure1C.svg", device = "svg", width = 3, height = 3.75)

```


