---
title: "table_one"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(tidyverse)
library(tableone)
library(forcats)
library(glue)
```


```{r}
cancer.copy <- c("1 non-small cell lung cancer
2 small cell lung cancer
3 melanoma
4 renal cell carcinoma
5 head and neck carcinoma
6 merkel cell carcinoma
7 Hodgkin lymphoma
8 breast cancer
9 colon cancer
10 pancreatic cancer
11 Sarcoma
12 Prostate
13 bladder cancer
14 AML
15 ALL
17 Other") %>%
  strsplit(., split = "\n") %>%
  unlist

cancer.key <- 
  data.frame(
    cancer =  cancer.copy %>%
      gsub("(\\d+).*", "\\1", .) %>%
      as.integer(),
    cancer.name = cancer.copy %>%
      gsub("\\d+ (.*)", "\\1", .),
    stringsAsFactors = FALSE
  )
```

load data
```{r}
db <- readRDS("T:/Labs/Spakowicz/data/exoio/table_one_db.RDS")
```

function
```{r}
check.window <- function(vect, per){
 wind <- per[1]:per[2]
 wind <- glue_collapse(as.character(wind), sep = ",|,")
 wind <- paste(",", wind, ",", sep = "")
 ifelse(grepl(pattern = wind, x = vect), 1, 0)
}
```

reduce db
```{r}
reduced <- db %>%
  filter(!is.na(cancer)) %>%
  filter(!tcc_id == "") %>%
  left_join(cancer.key) %>%
  mutate(abxdays.to.iostart = paste(",", abxdays.to.iostart, ",", sep = ""),
        sterdays.to.start = paste(",", sterdays.to.start, ",", sep = ""),
        abx.28.28 = check.window(abxdays.to.iostart, c(-28,28)),
        steroid.28.28 = check.window(sterdays.to.start, c(-28,28)))
```

summary
```{r}
summary <- reduced %>%
  group_by(cancer.name) %>%
  summarise(n()) %>%
  filter(`n()` > 10) %>%
  filter(!cancer.name == "Other")
```
```{r}
# Create key for naming immunotherapy codes
ionames <- data.frame(immunotherapy = c(1,2,3,4,5,6,7,8,9,10), 
                      Immunotherapy = c("Nivolumab", "Pembrolizumab", 
                                        "Atezolizumab", "Ipilimumab", 
                                        "Nivolumab + Ipilimumab", 
                                        "Durvalumab + Tremelimumab", 
                                        "Tremelimumab", "Nivolumab + Chemotherapy",
                                        "Durvalumab", "Other"),
                      stringsAsFactors = FALSE)

# Select and adjust dataframe for Table 1
coxdf <- reduced[which(reduced$cancer.name %in% c(summary$cancer.name)),] %>%
  select(vitalstatus, age, bmi.calc, ecog, sex, cancer.name, statin, ppi, 
         nsaid_iostart, h2b_iostart, immunotherapy, other_io, staging, abx.28.28,
         steroid.28.28,comorb.score) %>%
  left_join(ionames) %>%
  mutate(`ECOG PS` = fct_relevel(ifelse(ecog > 2, ">2", ecog), "0","1","2",">2"),
         Staging  = ifelse(staging == 5, "Unknown", staging),
         BMI = bmi.calc,
         Age = age,
         Cancer = cancer.name, 
         CCI = ifelse(comorb.score <= 1, "0-1", ">2"),
         Sex = sex,
         `ABx within 28 days of ICI` = abx.28.28,
         `CS within 28 days of ICI` = steroid.28.28,
          Immunotherapy = ifelse(Immunotherapy == "Nivolumab + Chemotherapy",
                                "Other", Immunotherapy),
         Immunotherapy = as.factor(Immunotherapy),
         Immunotherapy = fct_relevel(Immunotherapy, "Atezolizumab", "Durvalumab",
                                     "Durvalumab + Tremelimumab", "Ipilimumab", 
                                     "Nivolumab", "Nivolumab + Ipilimumab", 
                                     "Pembrolizumab", "Tremelimumab", "Other"),
         PPI = ppi)
```
##CHECK MEDICATION; check p val for different catagory between CCI/ECOG &PPI
# Creating table 1

```{r}
listVars <- c("BMI", "Age", "Sex", "ECOG PS", "CCI", "Cancer", "Staging", "Immunotherapy",
              "ABx within 28 days of ICI", "CS within 28 days of ICI","PPI")
catVars <- c("Sex", "Cancer", "Immunotherapy", "ECOG PS", "CCI", "Staging", 
             "ABx within 28 days of ICI", "CS within 28 days of ICI","PPI")
table1 <- CreateTableOne(vars = listVars,
                         data = coxdf,
                         factorVars = catVars)
tbl <- print(table1)
write.csv(tbl, "T:/Labs/Spakowicz/data/exoio/table1.csv")

COMPARE <- coxdf %>%
  group_by(CCI, PPI) %>%
  tally()

ggplot(coxdf,aes(x=CCI, y=PPI, fill = PPI))+
  geom_bar(stat="identity")
```
