---
title: "table one"
author: "Anna Petouhoff"
date: "2025-02-14"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(tidyverse)
library(tableone)
library(forcats)
library(glue)
library(eeptools)
library(readxl)
```

# load data
```{r}
CoRR <- read.csv("T:/Labs/Spakowicz/ppiio/data/derived/2025-02-17/CoRR_formatted.csv")
P188 <- read.csv("T:/Labs/Spakowicz/ppiio/data/derived/2025-02-17/P188_formatted.csv")
```



```{r}
# Create key for naming immunotherapy codes
ionames <- data.frame(immunotherapy = c(1,2,3,4,5,6,7,8,9,10), 
                      Immunotherapy = c("Nivolumab", "Pembrolizumab", 
                                        "Atezolizumab", "Ipilimumab", 
                                        "Nivolumab + Ipilimumab", 
                                        "Durvalumab + Tremelimumab", 
                                        "Tremelimumab", "Nivolumab + Chemotherapy",
                                        "Durvalumab", "Other"),
                      stringsAsFactors = FALSE)

# Select and adjust dataframe for Table 1
CoRR_df <- 
  CoRR %>%
  left_join(ionames) %>%
  mutate(`ECOG PS` = fct_relevel(ifelse(ecog > 2, ">2", ecog), "0","1","2",">2"),
         Staging  = ifelse(staging == 5, "Unknown", staging),
         BMI = bmi,
         Age = age,
         follow_up_time=follow_up,
         Sex = sex,
         Therapy = ifelse(line_of_therapy == 1,"1",">1"),
         Chemo_prior = prior_chemo)
P188_df <- 
  P188 %>%
  left_join(ionames) %>%
  mutate(`ECOG PS` = fct_relevel(ifelse(ecog > 2, ">2", ecog), "0","1","2",">2"),
         Staging  = ifelse(staging == 5, "Unknown", staging),
         BMI = bmi,
         Age = age,
         follow_up_time=follow_up,
         Sex = sex,
         Therapy = ifelse(line_of_therapy == 1,"1",">1"),
         Chemo_prior = prior_chemo)
```

Adjust the immunotherapy to four categories
```{r}
CoRR_df <- 
  CoRR_df %>%
  mutate(Immunotherapy = if_else(grepl("Atezo|Durvalumab$|Nivolumab$|Pembro",
                                           Immunotherapy),
                                     true = "PD1/L1",
                                     false = Immunotherapy),
         Immunotherapy = if_else(grepl("Durvalumab \\+ Tremelimumab$|Nivolumab \\+ Ipilimumab$",
                                           Immunotherapy),
                                     true = "PD1/L1 + CTLA4",
                                     false = Immunotherapy),
         Immunotherapy = if_else(grepl("Tremelimumab$|Ipilimumab$",
                                           Immunotherapy),
                                     true = "CTLA4",
                                     false = Immunotherapy),
         Immunotherapy = if_else(grepl("Nivolumab \\+ Chemotherapy",
                                           Immunotherapy),
                                     true = "Other",
                                     false = Immunotherapy),
         Immunotherapy = fct_relevel(Immunotherapy, c("PD1/L1", "CTLA4", "PD1/L1 + CTLA4", "Other")))

P188_df <- 
  P188_df %>%
  mutate(Immunotherapy = if_else(grepl("Atezo|Durvalumab$|Nivolumab$|Pembro",
                                           Immunotherapy),
                                     true = "PD1/L1",
                                     false = Immunotherapy),
         Immunotherapy = if_else(grepl("Durvalumab \\+ Tremelimumab$|Nivolumab \\+ Ipilimumab$",
                                           Immunotherapy),
                                     true = "PD1/L1 + CTLA4",
                                     false = Immunotherapy),
         Immunotherapy = if_else(grepl("Tremelimumab$|Ipilimumab$",
                                           Immunotherapy),
                                     true = "CTLA4",
                                     false = Immunotherapy),
         Immunotherapy = if_else(grepl("Nivolumab \\+ Chemotherapy",
                                           Immunotherapy),
                                     true = "Other",
                                     false = Immunotherapy),
         Immunotherapy = fct_relevel(Immunotherapy, c("PD1/L1", "CTLA4", "PD1/L1 + CTLA4", "Other")))
         
```

# Table 1 for CoRR
```{r}
listVars <- c("Age", "Sex", "vitalstatus","ECOG PS", "Cancer", "Staging", "Immunotherapy","Chemo_prior", "follow_up_time")
catVars <- c("Sex", "Cancer", "vitalstatus","Immunotherapy", "ECOG PS","Chemo_prior", "Staging")
table1 <- CreateTableOne(vars = listVars,
                         data = CoRR_df,
                         factorVars = catVars,
                         strata = c("ppi"))
tbl1.ppi <- print(table1, nonnormal = "follow_up_time")
write.csv(tbl1.ppi, "../../tables/table1.csv")
```

# Table 2 for P188
```{r}
listVars2 <- c("Age", "Sex", "vitalstatus","ECOG PS", "Immunotherapy","Chemo_prior","follow_up_time")
catVars2 <- c("Sex", "vitalstatus","Immunotherapy", "ECOG PS","Chemo_prior")
table2 <- CreateTableOne(vars = listVars2,
                         data = P188_df,
                         factorVars = catVars2,
                         strata = c("ppi"))
tbl2 <- print(table2, nonnormal = "follow_up_time")
write.csv(tbl2, "../../tables/table2.csv")
```


