---
title: "The effect of PPIs on survival"
author: "Rebecca Hoyd"
date: "January 7, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(ggplot2)
library(survival)
library(survminer)
```


# Load data

```{r load data}
db.old <- read.csv("T:/Labs/Spakowicz/data/co-med-io/clindat_2020-05-01.csv", stringsAsFactors = F)
cancer.key <- unique(db.old[, c("cancer", "cancer.name")])

db <- read.csv("T:/Labs/Spakowicz/projects/ppiio/data/raw/CoRR4684/2021-01-27/CoRR4684ARetrospecti_DATA_2021-01-27_1430.csv", stringsAsFactors = F) %>%
  left_join(cancer.key) %>%
  mutate(deathdate = ifelse(deathdate == "", NA, deathdate),
         lastcontact = ifelse(lastcontact == "", NA, lastcontact)) %>%
  mutate(eventdate = coalesce(deathdate, lastcontact)) %>%
  mutate(eventdate = as.POSIXct(eventdate, format = "%F"),
         iostart = as.POSIXct(iostart, format = "%F")) %>%
  mutate(days = eventdate - iostart) %>%
  filter(vitalstatus != 3) %>%
  mutate(vitalstatus = ifelse(vitalstatus == 1, 1, 0))
cancers <- cancer.key$cancer.name
```


# Survival: All samples

```{r}
all_surv <- survfit(Surv(days, vitalstatus) ~ ppi, data = db)

ggsurvplot(all_surv, pval = T, risk.table = T)
```

# Survival: Split cancers

## Create models

```{r}
mods.list <- list()

for(d in cancers){
  tmp <- db %>%
    filter(cancer.name == d)
  tmp.fit <- surv_fit(Surv(days, vitalstatus) ~ ppi, data = tmp)
  mods.list[[d]] <- tmp.fit
}
```

## Display plots

```{r}
lapply(cancers, function(x) try(ggsurvplot(mods.list[[x]], pval = T, risk.table = T, title = x)))
```

