---
title: "match-slids"
author: "Dan Spakowicz"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

# Tdrive is the ppiio folder on the lab share (gitignored 00-paths.R).
this_dir <- if (!is.null(knitr::current_input())) {
  dirname(normalizePath(knitr::current_input()))
} else {
  getwd()
}
paths_file <- file.path(this_dir, "..", "..", "manuscript", "scripts", "00-paths.R")
if (!file.exists(paths_file)) {
  stop(
    "Missing 00-paths.R. Copy manuscript/scripts/00-paths.R.example to ",
    "00-paths.R and set Tdrive to the ppiio folder on the lab share."
  )
}
source(paths_file)
if (!exists("Tdrive") || !nzchar(Tdrive)) {
  stop("00-paths.R must define Tdrive as the ppiio project folder on the lab share.")
}
```

```{r}
x <- read.csv(file.path(Tdrive, "data/slids.csv")) %>%
  rename("SLid" = "RNA.SLID")

head(x)
```

```{r}
files <- list.files(file.path("T:", "Labs", "Spakowicz", 
                     "projects", "exotic", "download_urls",
                     "fastq", "2021-02-22"),
                    full.names = TRUE)

files
```

```{r}
z <- lapply(files, function(x) readLines(x) %>% 
              data.frame)
names(z) <- gsub(".*/(.*)_DNAnexus.*", "\\1", files)
for (i in 1:length(z)) {
  z[[i]] <- 
    z[[i]] %>%
    mutate(cancer = names(z)[i])
}

id.can <- 
  z %>%
  bind_rows() %>%
  dplyr::rename("url" = ".") %>%
  mutate(SLid = gsub("http.*/(SL.*)_[1,2]\\.fastq\\.gz", "\\1", url)) %>%
  select(-url) %>%
  filter(!duplicated(SLid))

dim(id.can)
```

```{r}
comb <- 
  id.can %>%
  inner_join(x)

dim(comb)
table(comb$cancer)
```

Ok good! We have access to all of them.